#!/usr/bin/env python3
"""
Adiciona um BANCO DE EXERCÍCIOS EXTRAS (teacherGuide.extraPractice) a cada lição
Confidence / Logistics da Czarnikow.

Por que: o professor pediu mais exercícios que NÃO estão no app, focados na gramática
de cada lição, sempre no tema business/logistics, + vocabulary building + perguntas
sobre a rotina/dia a dia do próprio aluno. Para aluno iniciante (A1), cada item já vem
com gabarito/resposta-modelo para o professor conduzir sem preparar nada.

Cada lição recebe 3 blocos:
  1. Gramática extra (8–12 itens com gabarito) — fill-in / transformação no tema logística.
  2. Vocabulary building (8 palavras novas de logística/business + tradução).
  3. Fale sobre você (6 perguntas sobre a rotina de trabalho do aluno + resposta-modelo).

Seguro/aditivo: só escreve teacherGuide.extraPractice das lições confidence/logistics.
Idempotente: re-rodar sobrescreve com o conteúdo autoral atual.
"""
import json, os

HERE = os.path.dirname(os.path.abspath(__file__))
COURSE = os.path.join(HERE, "..", "courses", "czarnikow", "course.json")


def grammar(title, note, pairs):
    return {"title": title, "note": note, "items": [{"q": q, "a": a} for q, a in pairs]}


def vocab(title, pairs):
    return {"title": title, "note": "Para cada palavra, peça ao aluno uma frase curta no tema.",
            "items": [{"q": en, "a": pt} for en, pt in pairs]}


def routine(title, pairs):
    return {"title": title, "note": "Perguntas sobre o dia a dia do aluno. Se travar, ofereça a estrutura-modelo e peça para completar.",
            "items": [{"q": q, "a": a} for q, a in pairs]}


CONTENT = {}

# ---------------- 1101 — Verbo to be (am / is / are) ----------------
CONTENT[1101] = [
    grammar("Exercício extra A — Complete com am / is / are (logística)",
            "Faça oralmente e depois no caderno. Gabarito em verde.",
            [("The truck ___ at the gate.", "is"),
             ("I ___ the warehouse assistant.", "am"),
             ("The containers ___ very heavy.", "are"),
             ("Sugar ___ our main product.", "is"),
             ("We ___ a small but fast team.", "are"),
             ("The driver ___ on the road now.", "is"),
             ("You ___ in charge of the delivery today.", "are"),
             ("The pallets ___ ready for loading.", "are"),
             ("My manager ___ in a meeting.", "is"),
             ("The forklift and the truck ___ in the yard.", "are")]),
    grammar("Exercício extra B — Pergunta (?) e negativa (not)",
            "Modelo: The truck is ready → Is the truck ready? / The truck is not ready.",
            [("The delivery is late.", "Is the delivery late? / The delivery is not (isn't) late."),
             ("The drivers are here.", "Are the drivers here? / The drivers are not (aren't) here."),
             ("I am ready to start.", "Am I ready to start? / I am not ready to start."),
             ("The warehouse is open.", "Is the warehouse open? / The warehouse is not open."),
             ("They are on time.", "Are they on time? / They are not (aren't) on time.")]),
    vocab("Vocabulary building — palavras de logística (além das 5 da aula)",
          [("pallet", "palete"), ("forklift", "empilhadeira"), ("container", "contêiner"),
           ("gate", "portão"), ("shift", "turno"), ("supplier", "fornecedor"),
           ("customer", "cliente"), ("load", "carga / carregar")]),
    routine("Fale sobre você — sua rotina com o verbo to be",
            [("What is your job?", "I am a / an ___ ."),
             ("Where is your company?", "My company is in ___ ."),
             ("Are you busy on Mondays?", "Yes, I am. / No, I am not."),
             ("Who is your manager?", "My manager is ___ ."),
             ("What is your main product or service?", "Our main product is ___ ."),
             ("Are your customers in Brazil or abroad?", "Our customers are ___ .")]),
]

# ---------------- 1102 — Pronomes pessoais ----------------
CONTENT[1102] = [
    grammar("Exercício extra A — Substitua pelo pronome certo (I, you, he, she, it, we, they)",
            "O aluno troca o sujeito pelo pronome correto.",
            [("Harry is a driver. ___ is from London.", "He"),
             ("Sophie and I work here. ___ are a team.", "We"),
             ("The trucks are old. ___ need repairs.", "They"),
             ("The warehouse is big. ___ is near the port.", "It"),
             ("Maria is the manager. ___ is in a meeting.", "She"),
             ("You and Tom are late. ___ are late.", "You"),
             ("The delivery is ready. ___ leaves at 8.", "It"),
             ("The drivers are tired. ___ finish at 6.", "They"),
             ("James is busy. ___ is on the phone.", "He"),
             ("The boxes are heavy. ___ are full of sugar.", "They")]),
    grammar("Exercício extra B — Pronome + to be (monte a frase)",
            "Modelo: (she / manager) → She is the manager.",
            [("(he / driver)", "He is the driver."),
             ("(we / a good team)", "We are a good team."),
             ("(they / at the dock)", "They are at the dock."),
             ("(it / a new truck)", "It is a new truck."),
             ("(I / the assistant)", "I am the assistant.")]),
    vocab("Vocabulary building — pessoas e funções do time",
          [("manager", "gerente"), ("assistant", "assistente"), ("supervisor", "supervisor"),
           ("colleague", "colega"), ("team", "equipe / time"), ("staff", "equipe / pessoal"),
           ("operator", "operador"), ("customer", "cliente")]),
    routine("Fale sobre você — seu time e seu trabalho",
            [("Who is your manager? Tell me about him/her.", "He / She is ___ ."),
             ("Do you work alone or in a team?", "I work ___ . / We are a team."),
             ("Who is your closest colleague?", "He / She is ___ ."),
             ("Is your office big? Describe it.", "It is ___ ."),
             ("Are your coworkers friendly?", "They are ___ ."),
             ("What do you and your team do every day?", "We ___ .")]),
]

# ---------------- 1103 — There is / There are ----------------
CONTENT[1103] = [
    grammar("Exercício extra A — Complete com There is / There are",
            "Singular → There is. Plural → There are.",
            [("___ a truck at the gate.", "There is"),
             ("___ five containers in the yard.", "There are"),
             ("___ a problem with the delivery.", "There is"),
             ("___ many boxes on the shelf.", "There are"),
             ("___ no drivers today.", "There are"),
             ("___ some sugar in the bag.", "There is"),
             ("___ two docks in the warehouse.", "There are"),
             ("___ a meeting at 9 a.m.", "There is")]),
    grammar("Exercício extra B — Pergunta: Is there...? / Are there...?",
            "Modelo: a forklift here → Is there a forklift here?",
            [("any pallets in the warehouse?", "Are there any pallets in the warehouse?"),
             ("a problem with the truck?", "Is there a problem with the truck?"),
             ("many trucks at the gate?", "Are there many trucks at the gate?"),
             ("a label on the box?", "Is there a label on the box?"),
             ("any deliveries today?", "Are there any deliveries today?")]),
    vocab("Vocabulary building — lugares e objetos do armazém",
          [("shelf", "prateleira"), ("aisle", "corredor"), ("dock", "doca"),
           ("loading bay", "área de carga"), ("yard", "pátio"), ("crate", "engradado"),
           ("label", "etiqueta"), ("box", "caixa")]),
    routine("Fale sobre você — o que existe no seu trabalho",
            [("What is there in your office?", "There is / There are ___ ."),
             ("How many people are there in your team?", "There are ___ ."),
             ("Is there a warehouse in your company?", "Yes, there is. / No, there isn't."),
             ("Are there many meetings in your week?", "There are ___ ."),
             ("What is there near your workplace?", "There is ___ ."),
             ("Is there a problem you solve every day?", "There is ___ .")]),
]

# ---------------- 1104 — Present Simple (rotinas) ----------------
CONTENT[1104] = [
    grammar("Exercício extra A — Present Simple (cuidado com o -s na 3ª pessoa)",
            "he / she / it → verbo + s. Modelo: She check__ → She checks.",
            [("The driver ___ (start) at 6 a.m.", "starts"),
             ("We ___ (load) the trucks every morning.", "load"),
             ("She ___ (check) the delivery list.", "checks"),
             ("They ___ (work) in the warehouse.", "work"),
             ("The truck ___ (leave) at 8 o'clock.", "leaves"),
             ("I ___ (send) the invoice.", "send"),
             ("He ___ (drive) to the port.", "drives"),
             ("The team ___ (finish) at 6 p.m.", "finishes"),
             ("Sugar ___ (arrive) on Mondays.", "arrives"),
             ("You ___ (pack) the boxes.", "pack")]),
    grammar("Exercício extra B — Negativa: don't / doesn't",
            "I/you/we/they → don't. he/she/it → doesn't.",
            [("The driver ___ work on Sundays.", "doesn't"),
             ("We ___ deliver at night.", "don't"),
             ("She ___ answer the phone after 6.", "doesn't"),
             ("They ___ use that route.", "don't"),
             ("He ___ start before 7.", "doesn't")]),
    vocab("Vocabulary building — verbos do dia a dia",
          [("to load", "carregar"), ("to unload", "descarregar"), ("to deliver", "entregar"),
           ("to check", "conferir"), ("to ship", "despachar"), ("to track", "rastrear"),
           ("to schedule", "agendar"), ("to handle", "manusear / lidar com")]),
    routine("Fale sobre você — sua rotina (Present Simple)",
            [("What time do you start work?", "I start at ___ ."),
             ("What do you do every morning?", "Every morning I ___ ."),
             ("How do you go to work?", "I go by ___ ."),
             ("When do you check your emails?", "I check my emails ___ ."),
             ("What time do you finish?", "I finish at ___ ."),
             ("What does your team do every day?", "We ___ .")]),
]

# ---------------- 1105 — Preposições de lugar ----------------
CONTENT[1105] = [
    grammar("Exercício extra A — Complete com in / on / at / under / next to",
            "Use a foto da lição ou objetos da sala para mostrar a posição.",
            [("The boxes are ___ the shelf.", "on"),
             ("The truck is ___ the gate.", "at"),
             ("The sugar is ___ the warehouse.", "in"),
             ("The pallet is ___ the table.", "under"),
             ("The office is ___ the loading bay.", "next to"),
             ("The driver is ___ the truck.", "in"),
             ("The label is ___ the box.", "on"),
             ("We meet ___ the dock.", "at"),
             ("The forklift is ___ the trucks.", "next to"),
             ("The documents are ___ the drawer.", "in")]),
    grammar("Exercício extra B — Responda: Where is it?",
            "O professor pergunta, o aluno responde com a preposição.",
            [("Where is the truck? (gate)", "It is at the gate."),
             ("Where are the boxes? (shelf)", "They are on the shelf."),
             ("Where is the office? (loading bay)", "It is next to the loading bay."),
             ("Where is the sugar? (warehouse)", "It is in the warehouse."),
             ("Where is the pallet? (truck)", "It is under / in the truck.")]),
    vocab("Vocabulary building — lugares da logística",
          [("port", "porto"), ("terminal", "terminal"), ("depot", "depósito"),
           ("platform", "plataforma"), ("corner", "canto / esquina"), ("entrance", "entrada"),
           ("storage area", "área de armazenagem"), ("exit", "saída")]),
    routine("Fale sobre você — onde fica cada coisa no seu trabalho",
            [("Where is your desk?", "My desk is ___ ."),
             ("Where is your company located?", "It is in ___ ."),
             ("What is next to your office?", "___ is next to my office."),
             ("Where do you have lunch?", "I have lunch at / in ___ ."),
             ("Where do you keep your documents?", "They are in ___ ."),
             ("Where is the nearest port or airport?", "It is in ___ .")]),
]

# ---------------- 1106 — Countable/uncountable (much, many, some, any) ----------------
CONTENT[1106] = [
    grammar("Exercício extra A — much / many / some / any",
            "many/much em perguntas e negativas; some em afirmativas; any em perguntas/negativas.",
            [("How ___ trucks do you have?", "many"),
             ("How ___ sugar is in the bag?", "much"),
             ("There are ___ boxes on the dock.", "some"),
             ("Is there ___ fuel in the truck?", "any"),
             ("We don't have ___ time.", "much"),
             ("There aren't ___ drivers today.", "many"),
             ("Do you need ___ help?", "any / some"),
             ("There is ___ water on the floor.", "some"),
             ("How ___ money does it cost?", "much"),
             ("We have ___ pallets in stock.", "some")]),
    grammar("Exercício extra B — Countable (C) ou Uncountable (U)?",
            "O aluno classifica e diz a/an (C) ou nada (U).",
            [("truck", "C — a truck"), ("sugar", "U — sugar"), ("box", "C — a box"),
             ("fuel", "U — fuel"), ("delivery", "C — a delivery"), ("cargo", "U — cargo"),
             ("document", "C — a document"), ("equipment", "U — equipment")]),
    vocab("Vocabulary building — contável vs incontável na logística",
          [("cargo", "carga (incontável)"), ("freight", "frete (incontável)"),
           ("goods", "mercadorias (plural)"), ("fuel", "combustível (incontável)"),
           ("equipment", "equipamento (incontável)"), ("package", "pacote (contável)"),
           ("document", "documento (contável)"), ("stock", "estoque (incontável)")]),
    routine("Fale sobre você — quantidades no seu trabalho",
            [("How many people work with you?", "___ people work with me."),
             ("How much time do you spend in meetings?", "I spend ___ ."),
             ("Do you have many emails every day?", "Yes, I have many. / No, not many."),
             ("Is there much paperwork in your job?", "There is ___ ."),
             ("How many tasks do you do daily?", "I do ___ tasks."),
             ("Do you need any special tools for your work?", "Yes, I need ___ . / No, I don't.")]),
]

# ---------------- 1107 — Imperativos e direções ----------------
CONTENT[1107] = [
    grammar("Exercício extra A — Imperativo (ordem/instrução)",
            "Imperativo = verbo no início, sem sujeito. Modelo: (turn / left) → Turn left.",
            [("___ left at the gate. (turn)", "Turn"),
             ("___ straight to the warehouse. (go)", "Go"),
             ("___ the first exit. (take)", "Take"),
             ("___ the boxes to the dock. (take)", "Take"),
             ("___ the truck at the platform. (park)", "Park"),
             ("Don't ___ the red door. (open)", "open"),
             ("___ the documents to the office. (bring)", "Bring"),
             ("___ here and wait. (stop)", "Stop"),
             ("___ the forklift slowly. (drive)", "Drive"),
             ("___ your badge at the entrance. (show)", "Show")]),
    grammar("Exercício extra B — Dê a direção (turn / go / take)",
            "O professor pede o caminho; o aluno responde com imperativos.",
            [("From the gate to the office?", "Go straight, then turn left."),
             ("How to reach the dock?", "Take the first exit and turn right."),
             ("Where is the exit?", "Go straight ahead. The exit is on the right."),
             ("How to find the warehouse?", "Turn left at the sign and go straight."),
             ("To the parking area?", "Take the second corner and stop there.")]),
    vocab("Vocabulary building — direções e instruções",
          [("left / right", "esquerda / direita"), ("straight ahead", "em frente"),
           ("exit", "saída"), ("corner", "esquina / canto"), ("entrance", "entrada"),
           ("floor", "andar / chão"), ("sign", "placa"), ("route", "rota")]),
    routine("Fale sobre você — dando instruções do seu trabalho",
            [("How do I get to your office from the entrance?", "Go ___ , turn ___ ."),
             ("Give one instruction you say at work every day.", "(ex.: 'Check the list.')"),
             ("What do you tell a new driver?", "(ex.: 'Park here and show your badge.')"),
             ("Describe the way from the door to your desk.", "Go ___ , take ___ ."),
             ("What is the first thing you do when you arrive?", "First, I ___ ."),
             ("Tell a colleague how to find the warehouse.", "Turn ___ and go ___ .")]),
]

# ---------------- 1108 — Horas (at + o'clock / half past / quarter) ----------------
CONTENT[1108] = [
    grammar("Exercício extra A — Que horas são? (half past, quarter to/past, o'clock)",
            "7:30 = half past seven · 8:15 = quarter past eight · 8:45 = quarter to nine.",
            [("The truck leaves ___ 8 o'clock.", "at"),
             ("7:30 = half ___ seven.", "past"),
             ("8:15 = quarter ___ eight.", "past"),
             ("8:45 = quarter ___ nine.", "to"),
             ("We start work ___ 6 a.m.", "at"),
             ("9:00 = nine ___ .", "o'clock"),
             ("The delivery arrives ___ noon.", "at"),
             ("5:45 = quarter to ___ .", "six"),
             ("Lunch is ___ half past twelve.", "at"),
             ("10:30 = half past ___ .", "ten")]),
    grammar("Exercício extra B — Escreva a hora por extenso",
            "O aluno lê o número e diz a hora em inglês.",
            [("6:00", "six o'clock"), ("7:15", "quarter past seven"),
             ("9:30", "half past nine"), ("11:45", "quarter to twelve"),
             ("2:30", "half past two"), ("8:00", "eight o'clock")]),
    vocab("Vocabulary building — tempo no trabalho",
          [("shift", "turno"), ("deadline", "prazo"), ("schedule", "cronograma / agenda"),
           ("on time", "no horário"), ("early", "cedo"), ("late", "atrasado"),
           ("break", "pausa / intervalo"), ("overtime", "hora extra")]),
    routine("Fale sobre você — seus horários",
            [("What time do you start work?", "I start at ___ ."),
             ("What time is your lunch break?", "It is at ___ ."),
             ("When do you finish?", "I finish at ___ ."),
             ("What time is your first meeting usually?", "Usually at ___ ."),
             ("When does your shift end?", "It ends at ___ ."),
             ("Are you usually early or late?", "I am usually ___ .")]),
]

# ---------------- 1109 — Adjetivos ----------------
CONTENT[1109] = [
    grammar("Exercício extra A — Escolha/coloque o adjetivo (logística)",
            "Em inglês o adjetivo vem ANTES do substantivo: a big truck (não 'a truck big').",
            [("It is a ___ truck. (new)", "a new truck"),
             ("The warehouse is very ___ . (large)", "large"),
             ("We need a ___ driver. (careful)", "careful"),
             ("The delivery is ___ . (late)", "late"),
             ("It is a ___ box. (heavy)", "a heavy box"),
             ("The road is ___ today. (busy)", "busy"),
             ("Our service is ___ . (reliable)", "reliable"),
             ("They have a ___ system. (modern)", "modern"),
             ("The sugar is ___ and ___ . (clean / dry)", "clean and dry"),
             ("It is a ___ company. (big, international)", "a big international company")]),
    grammar("Exercício extra B — Descreva com 2 adjetivos",
            "O aluno usa dois adjetivos juntos na ordem certa (opinião + tamanho/cor...).",
            [("truck (big / red)", "a big red truck"),
             ("warehouse (new / large)", "a new large warehouse → a large new warehouse"),
             ("driver (good / fast)", "a good fast driver"),
             ("delivery (small / urgent)", "a small urgent delivery"),
             ("box (old / heavy)", "an old heavy box")]),
    vocab("Vocabulary building — adjetivos úteis no trabalho",
          [("reliable", "confiável"), ("efficient", "eficiente"), ("heavy / light", "pesado / leve"),
           ("fast / slow", "rápido / lento"), ("safe", "seguro"), ("busy", "ocupado / movimentado"),
           ("urgent", "urgente"), ("careful", "cuidadoso")]),
    routine("Fale sobre você — descreva seu trabalho com adjetivos",
            [("Describe your company in two adjectives.", "My company is ___ and ___ ."),
             ("Is your job busy or quiet?", "My job is ___ ."),
             ("Describe a good driver / professional.", "A good ___ is ___ ."),
             ("How is your typical day?", "It is ___ ."),
             ("Describe your team.", "My team is ___ ."),
             ("What makes a good delivery?", "A good delivery is ___ .")]),
]

# ---------------- 1110 — Modais can / could ----------------
CONTENT[1110] = [
    grammar("Exercício extra A — can / could (habilidade e pedidos)",
            "can = poder/saber · could = pedido mais educado. Sempre + verbo no infinitivo sem 'to'.",
            [("___ you help me with the boxes? (pedido)", "Can / Could"),
             ("The truck ___ carry 20 tonnes.", "can"),
             ("___ you repeat that, please? (educado)", "Could"),
             ("I ___ drive a forklift.", "can"),
             ("We ___ deliver tomorrow.", "can"),
             ("___ I speak to the manager, please?", "Could / Can"),
             ("He ___ not come today.", "can / could"),
             ("___ you send the invoice?", "Can / Could"),
             ("Drivers ___ park here.", "can"),
             ("___ you check the address for me?", "Could / Can")]),
    grammar("Exercício extra B — Peça com educação (telefone do motorista)",
            "Transforme em pedido educado com Could you...?",
            [("send the documents", "Could you send the documents, please?"),
             ("confirm the address", "Could you confirm the address, please?"),
             ("call back later", "Could you call back later, please?"),
             ("wait five minutes", "Could you wait five minutes, please?"),
             ("repeat the order number", "Could you repeat the order number, please?")]),
    vocab("Vocabulary building — telefone e pedidos",
          [("to help", "ajudar"), ("to repeat", "repetir"), ("to confirm", "confirmar"),
           ("to call back", "retornar a ligação"), ("to hold on", "aguardar na linha"),
           ("request", "pedido"), ("available", "disponível"), ("urgent", "urgente")]),
    routine("Fale sobre você — o que você sabe/pode fazer no trabalho",
            [("What can you do at work?", "I can ___ ."),
             ("Can you drive?", "Yes, I can. / No, I can't."),
             ("Could you help a new colleague?", "Yes, I could ___ ."),
             ("What languages can you speak?", "I can speak ___ ."),
             ("Can you use a computer system at work?", "Yes, I can use ___ ."),
             ("What can your company do for clients?", "We can ___ .")]),
]

# ---------------- 1111 — have / has ----------------
CONTENT[1111] = [
    grammar("Exercício extra A — have / has (posse e informações)",
            "I/you/we/they → have · he/she/it → has.",
            [("We ___ three trucks.", "have"),
             ("The driver ___ a new phone.", "has"),
             ("I ___ the delivery list.", "have"),
             ("The warehouse ___ two floors.", "has"),
             ("They ___ many customers.", "have"),
             ("She ___ the documents.", "has"),
             ("The truck ___ a GPS.", "has"),
             ("You ___ a meeting at 10.", "have"),
             ("Our company ___ an office in London.", "has"),
             ("The boxes ___ labels.", "have")]),
    grammar("Exercício extra B — Pergunta com do/does + have",
            "Modelo: (you / a truck) → Do you have a truck?",
            [("(the company / many clients)", "Does the company have many clients?"),
             ("(you / the invoice)", "Do you have the invoice?"),
             ("(the truck / a GPS)", "Does the truck have a GPS?"),
             ("(they / a meeting today)", "Do they have a meeting today?"),
             ("(she / the documents)", "Does she have the documents?")]),
    vocab("Vocabulary building — nota fiscal e documentos",
          [("invoice", "nota fiscal / fatura"), ("order", "pedido"), ("receipt", "recibo"),
           ("quantity", "quantidade"), ("price", "preço"), ("total", "total"),
           ("reference number", "número de referência"), ("customer", "cliente")]),
    routine("Fale sobre você — o que você tem no trabalho",
            [("How many people do you have in your team?", "We have ___ ."),
             ("Do you have a busy schedule?", "Yes, I have ___ . / No, I don't."),
             ("What equipment do you have at work?", "We have ___ ."),
             ("Does your company have many clients?", "It has ___ ."),
             ("What documents do you have on your desk?", "I have ___ ."),
             ("Do you have meetings every day?", "I have ___ meetings.")]),
]

# ---------------- 1112 — was / were ----------------
CONTENT[1112] = [
    grammar("Exercício extra A — was / were (passado de to be)",
            "I/he/she/it → was · you/we/they → were.",
            [("The delivery ___ late yesterday.", "was"),
             ("The drivers ___ tired.", "were"),
             ("I ___ at the warehouse this morning.", "was"),
             ("The trucks ___ ready at 8.", "were"),
             ("It ___ a good day.", "was"),
             ("We ___ very busy last week.", "were"),
             ("The road ___ closed.", "was"),
             ("You ___ on time.", "were"),
             ("The boxes ___ heavy.", "were"),
             ("She ___ the supervisor last year.", "was")]),
    grammar("Exercício extra B — Pergunta e negativa no passado",
            "Modelo: The truck was ready → Was the truck ready? / The truck wasn't ready.",
            [("The delivery was on time.", "Was the delivery on time? / The delivery wasn't on time."),
             ("The drivers were here.", "Were the drivers here? / The drivers weren't here."),
             ("It was a busy day.", "Was it a busy day? / It wasn't a busy day."),
             ("You were at the meeting.", "Were you at the meeting? / You weren't at the meeting."),
             ("The trucks were full.", "Were the trucks full? / The trucks weren't full.")]),
    vocab("Vocabulary building — falando de um dia passado",
          [("yesterday", "ontem"), ("last week", "semana passada"), ("on time", "no horário"),
           ("delay", "atraso"), ("problem", "problema"), ("success", "sucesso"),
           ("busy", "movimentado"), ("quiet", "tranquilo")]),
    routine("Fale sobre você — ontem / semana passada",
            [("How was your day yesterday?", "It was ___ ."),
             ("Were you busy last week?", "Yes, I was. / No, I wasn't."),
             ("Where were you this morning?", "I was ___ ."),
             ("Was the traffic bad today?", "It was ___ ."),
             ("Were your deliveries on time yesterday?", "They were ___ ."),
             ("How was your last meeting?", "It was ___ .")]),
]

# ---------------- 1113 — It is + weather / traffic ----------------
CONTENT[1113] = [
    grammar("Exercício extra A — It is + clima / trânsito",
            "Para clima e trânsito usamos 'It is...' (não traduza 'está' por outra coisa).",
            [("___ cold this morning.", "It is"),
             ("___ sunny today.", "It is"),
             ("___ foggy near the port.", "It is"),
             ("___ very hot in the warehouse.", "It is"),
             ("___ windy at the dock.", "It is"),
             ("The traffic ___ heavy today.", "is"),
             ("___ raining, so the delivery is late.", "It is"),
             ("___ a good day for driving.", "It is"),
             ("The road ___ busy now.", "is"),
             ("___ snowing in the mountains.", "It is")]),
    grammar("Exercício extra B — Pergunta sobre o clima/trânsito",
            "Modelo: (cold) → Is it cold?",
            [("(sunny)", "Is it sunny?"),
             ("(raining)", "Is it raining?"),
             ("(traffic / heavy)", "Is the traffic heavy?"),
             ("(road / closed)", "Is the road closed?"),
             ("(foggy at the port)", "Is it foggy at the port?")]),
    vocab("Vocabulary building — clima e estrada",
          [("sunny", "ensolarado"), ("rainy", "chuvoso"), ("foggy", "com neblina"),
           ("windy", "ventando"), ("traffic jam", "engarrafamento"), ("heavy traffic", "trânsito intenso"),
           ("slippery", "escorregadio"), ("delay", "atraso")]),
    routine("Fale sobre você — clima, trânsito e o trabalho",
            [("How is the weather today?", "It is ___ ."),
             ("Is the traffic bad in your city?", "It is ___ ."),
             ("How do you go to work when it is raining?", "When it rains, I ___ ."),
             ("Does the weather affect your deliveries?", "Yes, when it is ___ , the delivery is ___ ."),
             ("What is the weather like in winter where you live?", "It is ___ ."),
             ("Is there much traffic in the morning?", "There is ___ .")]),
]

# ---------------- 1114 — Comparativos ----------------
CONTENT[1114] = [
    grammar("Exercício extra A — Comparativos (curtos: +er · longos: more...)",
            "fast→faster · safe→safer · good→better · expensive→more expensive.",
            [("The plane is ___ (fast) than the truck.", "faster"),
             ("This road is ___ (safe) than the highway.", "safer"),
             ("The new truck is ___ (big) than the old one.", "bigger"),
             ("Sea freight is ___ (cheap) than air freight.", "cheaper"),
             ("Today is ___ (busy) than yesterday.", "busier"),
             ("This box is ___ (heavy) than that one.", "heavier"),
             ("The new route is ___ (short) than the old one.", "shorter"),
             ("Air freight is ___ (expensive) than sea freight.", "more expensive"),
             ("This supplier is ___ (reliable) than the other.", "more reliable"),
             ("Our service is ___ (good) than before.", "better")]),
    grammar("Exercício extra B — Compare os dois (faça a frase)",
            "Modelo: (plane / fast / truck) → The plane is faster than the truck.",
            [("(sea freight / cheap / air freight)", "Sea freight is cheaper than air freight."),
             ("(this route / safe / that route)", "This route is safer than that route."),
             ("(morning shift / long / night shift)", "The morning shift is longer than the night shift."),
             ("(new system / good / old system)", "The new system is better than the old system."),
             ("(truck A / heavy / truck B)", "Truck A is heavier than truck B.")]),
    vocab("Vocabulary building — comparando transporte",
          [("faster / slower", "mais rápido / mais lento"), ("cheaper / more expensive", "mais barato / mais caro"),
           ("safer", "mais seguro"), ("shorter / longer", "mais curto / mais longo"),
           ("heavier / lighter", "mais pesado / mais leve"), ("better / worse", "melhor / pior"),
           ("reliable", "confiável"), ("efficient", "eficiente")]),
    routine("Fale sobre você — comparações do seu dia a dia",
            [("Which is faster for you: car or bus?", "___ is faster."),
             ("Is your job busier on Mondays or Fridays?", "It is busier on ___ ."),
             ("Compare this year and last year at work.", "This year is ___ than last year."),
             ("Which is better for delivery: morning or afternoon?", "___ is better."),
             ("Is your city bigger than your hometown?", "Yes/No, it is ___ ."),
             ("What is more important: speed or safety?", "___ is more important.")]),
]

# ---------------- 1115 — from / to ----------------
CONTENT[1115] = [
    grammar("Exercício extra A — from / to (origem e destino)",
            "from = de (origem) · to = para (destino).",
            [("The truck goes ___ Santos ___ São Paulo.", "from / to"),
             ("We ship sugar ___ Brazil ___ Europe.", "from / to"),
             ("The delivery is ___ the warehouse ___ the client.", "from / to"),
             ("The flight is ___ London ___ New York.", "from / to"),
             ("The road ___ the port ___ the city is busy.", "from / to"),
             ("He drives ___ Monday ___ Friday.", "from / to"),
             ("The price is ___ 100 ___ 200 dollars.", "from / to"),
             ("We are open ___ 8 a.m. ___ 6 p.m.", "from / to"),
             ("The container travels ___ China ___ Brazil.", "from / to"),
             ("We deliver ___ door ___ door.", "from / to")]),
    grammar("Exercício extra B — Descreva o trajeto",
            "O aluno completa com from...to e cidades reais.",
            [("Where does the sugar go?", "From Santos to London."),
             ("What are the office hours?", "From 8 a.m. to 6 p.m."),
             ("What days do you work?", "From Monday to Friday."),
             ("Where does the truck travel?", "From the port to the depot."),
             ("What is the price range?", "From 100 to 200 dollars.")]),
    vocab("Vocabulary building — origem e destino",
          [("origin", "origem"), ("destination", "destino"), ("route", "rota / trajeto"),
           ("distance", "distância"), ("departure", "partida / saída"), ("arrival", "chegada"),
           ("shipment", "remessa / carga"), ("delivery point", "ponto de entrega")]),
    routine("Fale sobre você — seus trajetos e horários",
            [("Where do you travel from and to for work?", "From ___ to ___ ."),
             ("What are your working hours?", "From ___ to ___ ."),
             ("How far is it from your home to your office?", "From home to office is about ___ ."),
             ("Where do your products go from and to?", "From ___ to ___ ."),
             ("What days do you work?", "From ___ to ___ ."),
             ("Describe a typical trip you make.", "I go from ___ to ___ .")]),
]

# ---------------- 1116 — Where is / Where are ----------------
CONTENT[1116] = [
    grammar("Exercício extra A — Where is / Where are",
            "Singular → Where is · Plural → Where are.",
            [("___ the truck? — It is at the gate.", "Where is"),
             ("___ the drivers? — They are at the dock.", "Where are"),
             ("___ my documents? — They are on the desk.", "Where are"),
             ("___ the warehouse? — It is near the port.", "Where is"),
             ("___ the boxes? — They are on the shelf.", "Where are"),
             ("___ the manager? — She is in a meeting.", "Where is"),
             ("___ the keys? — They are in the office.", "Where are"),
             ("___ the delivery? — It is on the way.", "Where is"),
             ("___ the forklift? — It is in the yard.", "Where is"),
             ("___ the pallets? — They are at the loading bay.", "Where are")]),
    grammar("Exercício extra B — Pergunte o status (telefone)",
            "O aluno faz a pergunta certa para cada situação.",
            [("(the shipment)", "Where is the shipment?"),
             ("(the trucks)", "Where are the trucks?"),
             ("(my order)", "Where is my order?"),
             ("(the containers)", "Where are the containers?"),
             ("(the driver)", "Where is the driver?")]),
    vocab("Vocabulary building — perguntando o status",
          [("location", "localização"), ("status", "situação / status"), ("on the way", "a caminho"),
           ("delayed", "atrasado"), ("arrived", "chegou"), ("in transit", "em trânsito"),
           ("pending", "pendente"), ("ready", "pronto")]),
    routine("Fale sobre você — onde estão as coisas no seu trabalho",
            [("Where is your office?", "It is in ___ ."),
             ("Where are your colleagues right now?", "They are ___ ."),
             ("Where do you keep your tools or documents?", "They are ___ ."),
             ("Where is your manager today?", "He / She is ___ ."),
             ("Where are your main clients?", "They are in ___ ."),
             ("Where do you usually have lunch?", "It is at ___ .")]),
]

# ---------------- 1117 — Dias da semana + on ----------------
CONTENT[1117] = [
    grammar("Exercício extra A — on + dia da semana",
            "Antes do dia da semana usamos 'on': on Monday, on Friday.",
            [("The delivery arrives ___ Monday.", "on"),
             ("We don't work ___ Sundays.", "on"),
             ("The meeting is ___ Friday.", "on"),
             ("Sugar comes ___ Wednesdays.", "on"),
             ("___ Saturday the warehouse is closed.", "On"),
             ("The driver rests ___ Sunday.", "on"),
             ("We ship ___ Tuesdays and Thursdays.", "on"),
             ("The report is due ___ Monday.", "on"),
             ("___ which day do you start?", "On"),
             ("The truck leaves ___ Monday morning.", "on")]),
    grammar("Exercício extra B — Diga o dia (rotina da semana)",
            "O aluno responde com on + dia.",
            [("When does the sugar arrive?", "On Wednesdays."),
             ("When is the meeting?", "On Friday."),
             ("When is the warehouse closed?", "On Saturday and Sunday."),
             ("When do you ship orders?", "On Tuesdays and Thursdays."),
             ("When is your day off?", "On Sunday.")]),
    vocab("Vocabulary building — semana e agenda",
          [("weekday", "dia útil"), ("weekend", "fim de semana"), ("daily", "diário"),
           ("weekly", "semanal"), ("day off", "folga"), ("working day", "dia de trabalho"),
           ("appointment", "compromisso"), ("routine", "rotina")]),
    routine("Fale sobre você — sua semana",
            [("What days do you work?", "I work on ___ ."),
             ("When is your day off?", "My day off is on ___ ."),
             ("What do you do on Mondays?", "On Mondays I ___ ."),
             ("When are your meetings?", "They are on ___ ."),
             ("What do you do on the weekend?", "On the weekend I ___ ."),
             ("Which is your busiest day?", "___ is my busiest day.")]),
]

# ---------------- 1118 — Simple Past (verbos regulares) ----------------
CONTENT[1118] = [
    grammar("Exercício extra A — Simple Past (verbos regulares + -ed)",
            "Passado regular = verbo + ed: work→worked, arrive→arrived.",
            [("The truck ___ (arrive) at 8.", "arrived"),
             ("We ___ (load) 20 pallets.", "loaded"),
             ("She ___ (check) the documents.", "checked"),
             ("They ___ (deliver) the boxes.", "delivered"),
             ("I ___ (call) the client.", "called"),
             ("He ___ (park) the truck.", "parked"),
             ("The team ___ (finish) early.", "finished"),
             ("The driver ___ (start) at 6.", "started"),
             ("We ___ (ship) the order yesterday.", "shipped"),
             ("The company ___ (open) a new depot.", "opened")]),
    grammar("Exercício extra B — Negativa e pergunta (did / didn't)",
            "Passado: did + verbo no infinitivo. Modelo: I worked → I didn't work / Did you work?",
            [("She checked the list.", "She didn't check the list. / Did she check the list?"),
             ("They delivered the boxes.", "They didn't deliver the boxes. / Did they deliver the boxes?"),
             ("We loaded the truck.", "We didn't load the truck. / Did we load the truck?"),
             ("He called the client.", "He didn't call the client. / Did he call the client?"),
             ("The truck arrived on time.", "The truck didn't arrive on time. / Did the truck arrive on time?")]),
    vocab("Vocabulary building — um dia de trabalho no passado",
          [("to arrive", "chegar"), ("to deliver", "entregar"), ("to load / unload", "carregar / descarregar"),
           ("to call", "ligar"), ("to finish", "terminar"), ("to solve", "resolver"),
           ("to receive", "receber"), ("to ship", "despachar")]),
    routine("Fale sobre você — o que você fez (passado)",
            [("What did you do yesterday at work?", "I ___ed ___ ."),
             ("What time did you arrive today?", "I arrived at ___ ."),
             ("Who did you talk to yesterday?", "I talked to ___ ."),
             ("What did you finish last week?", "I finished ___ ."),
             ("Did you call any clients yesterday?", "Yes, I called ___ . / No, I didn't."),
             ("What problem did you solve recently?", "I solved ___ .")]),
]

# ---------------- 1119 — Agradecimento e educação ----------------
CONTENT[1119] = [
    grammar("Exercício extra A — Qual a expressão certa?",
            "Situação → resposta educada. O aluno escolhe/completa.",
            [("Someone helps you. You say:", "Thank you (very much)."),
             ("Someone says thank you. You answer:", "You're welcome."),
             ("You want to ask something. You start with:", "Excuse me, ... / Could you ...?"),
             ("You make a mistake. You say:", "I'm sorry."),
             ("You meet a client for the first time:", "Nice to meet you."),
             ("You leave the office:", "Goodbye. / Have a nice day."),
             ("Ask a favor politely: ___ you help me?", "Could / Can"),
             ("You give something to someone: ___ you are.", "Here"),
             ("Thank someone a lot: Thanks ___ your help.", "for"),
             ("End of a work email: ___ regards,", "Best / Kind")]),
    grammar("Exercício extra B — O que você diz? (situações reais)",
            "O professor lê a situação; o aluno responde com a frase educada.",
            [("A driver brings the delivery on time.", "Thank you very much!"),
             ("A client says 'thank you'.", "You're welcome."),
             ("You need to pass by someone.", "Excuse me."),
             ("You are 10 minutes late.", "I'm sorry I'm late."),
             ("You finish a call with a customer.", "Thank you for your time. Goodbye.")]),
    vocab("Vocabulary building — educação no trabalho",
          [("please", "por favor"), ("thank you / thanks", "obrigado(a)"), ("you're welcome", "de nada"),
           ("excuse me", "com licença"), ("I'm sorry", "desculpe"), ("of course", "claro"),
           ("no problem", "sem problema"), ("have a nice day", "tenha um bom dia")]),
    routine("Fale sobre você — educação nas suas situações reais",
            [("How do you greet a colleague in the morning?", "I say: ___ ."),
             ("What do you say when a client thanks you?", "I say: You're welcome."),
             ("How do you ask for help politely?", "Could you ___ , please?"),
             ("How do you end a work email?", "Best regards, / Kind regards,"),
             ("What do you say when you arrive late?", "I'm sorry, I'm late because ___ ."),
             ("How do you say goodbye to a customer?", "Thank you. Have a nice day!")]),
]

# ---------------- 1120 — Revisão geral ----------------
CONTENT[1120] = [
    grammar("Exercício extra A — Revisão mista (tudo do Confidence)",
            "Mistura to be, there is/are, present simple, can, past, preposições, comparativo, from/to.",
            [("The truck ___ (be) at the gate.", "is"),
             ("There ___ (be) five containers.", "are"),
             ("We ___ (load) the trucks every morning.", "load"),
             ("___ you help me, please?", "Can / Could"),
             ("The delivery ___ (be) late yesterday.", "was"),
             ("The boxes are ___ the shelf.", "on"),
             ("The plane is ___ (fast) than the truck.", "faster"),
             ("We ship ___ Santos ___ London.", "from / to"),
             ("___ are the drivers? — At the dock.", "Where"),
             ("The team ___ (finish) early yesterday.", "finished")]),
    grammar("Exercício extra B — Corrija a frase (erro comum)",
            "O aluno encontra e corrige o erro.",
            [("The trucks is ready.", "The trucks ARE ready."),
             ("She have two deliveries.", "She HAS two deliveries."),
             ("There is many boxes.", "There ARE many boxes."),
             ("He don't work on Sundays.", "He DOESN'T work on Sundays."),
             ("The plane is more fast than the truck.", "The plane is FASTER than the truck.")]),
    vocab("Vocabulary building — palavras-chave da trilha",
          [("warehouse", "armazém"), ("delivery", "entrega"), ("shipment", "remessa"),
           ("supplier", "fornecedor"), ("customer", "cliente"), ("invoice", "fatura"),
           ("route", "rota"), ("schedule", "cronograma")]),
    routine("Fale sobre você — apresente o seu trabalho (revisão geral)",
            [("What is your job and where do you work?", "I am ___ and I work in ___ ."),
             ("Describe your daily routine.", "Every day I ___ ."),
             ("What did you do yesterday?", "Yesterday I ___ed ___ ."),
             ("What can you do well at work?", "I can ___ ."),
             ("How was your week?", "It was ___ ."),
             ("Tell me about your team.", "We are ___ and we ___ .")]),
]


def main():
    with open(COURSE, encoding="utf-8") as f:
        d = json.load(f)

    changed = 0
    for l in d["lessons"]:
        if l.get("track") != "logistics" or l.get("level") != "confidence":
            continue
        blocks = CONTENT.get(l["num"])
        if not blocks:
            continue
        tg = l.get("teacherGuide")
        if not isinstance(tg, dict):
            tg = {}
            l["teacherGuide"] = tg
        tg["extraPractice"] = blocks
        changed += 1

    if changed:
        with open(COURSE, "w", encoding="utf-8") as f:
            json.dump(d, f, ensure_ascii=False, indent=1)
    print(f"extraPractice adicionado em {changed} lições (esperado 20).")


if __name__ == "__main__":
    main()
